### ISSUE TITLE
Disable the plugin on localhost

### ISSUE THREAD

**Issue by yani-** [rlankhorst/really-simple-ssl#101]
**The issue**
SSL is not supported on localhost and loopback IP addresses 127.0.0.0 to 127.255.255.255. Enabling SSL will lock the user out and break their WordPress install. 

**Please describe what you expected to happen and why:**
I expect the plugin to display a warning message and to refuse to enable SSL when enabled on unsupported address.

**How can we reproduce this behavior?**
Install WordPress on localhost. Install and activate the plugin. Attempt to browse any of the pages or wp-admin area.

**Comment by rlankhorst** [comment]
Hi, 

The plugin does a simple check for SSL by loading a testpage over https, but does not check for the validity of the certificate. This means that when there is no SSL certificate, you get a warning, as expected. But if you do have an SSL certificate, but it's self signed, or the domain is not correct for example, the plugin will not see that, and will show a button to enable. I've just tested this on localhost, and got the "no SSL detected" warning. Possibly you have a self signed certificate installed. 

We're currently working to implement an extended SSL verification library, which would prevent issues such as yours. 

If you want to disable the plugin while not being able to access the back-end, you can use the force-deactivate file, as described here:
https://really-simple-ssl.com/knowledge-base/uninstall-websitebackend-not-accessible/

**Comment by yani-** [comment]
I am thinking of the following flow.

When the request arrives via https, the plugin should work as is.

When the request arrives via http, the plugin does a curl request to verify if the site is available via https - if yes, 301 the user to https
- if no, only allow logging into wpadmin and display a red warning message telling user that their site does not work under https anymore.

What do you think?

**Comment by rlankhorst** [comment]
There are some drawbacks on a check based on the request.
- Most websites use .htaccess redirect to https. As this redirects before the site is loaded, the http request will not reach the site. 
- Assuming .htaccess redirect is disabled, this would mean that on the live site, where a lot of requests can come in over http (especially in the first weeks of the switch to SSL), this verification is performed on each http request, which is bad for performance. 

Because of the .htaccess redirect, I don't think there is an automated solution possible, other than deactivating using the force-deactivate script, or installing a local self signed SSL certificate which should make it possible to load the site over https. 

Let me know what you think!
