### ISSUE TITLE
Cannot access woocommerce rest API

### ISSUE THREAD

**Issue by amirvenus** [rlankhorst/really-simple-ssl#143]
Hi,

After enabling this plugin, I am unable to access the WC's REST API giving me a 401 (unathorised error) whereas disabling this plugin, lets me back in to the API.

**Comment by rlankhorst** [comment]
Hi, 

What happens if you use the option "deactivate, but keep https" in settings/ssl/settings?

**Comment by amirvenus** [comment]
It works on the woocommerce app although I haven't tested the .net wrapper yet but I suppose that will work too. 

The only problem is the mixed-content (reading from http still) .

Would it not be nice to fix this issue so we can continue having this lovely plugin enabled and use the REST API at the same time as well? 

According to:

https://robotninja.com/blog/fix-common-woocommerce-rest-api-issues/

I think the problem is the headers being lost in redirection

**Comment by rlankhorst** [comment]
The issue then is the redirect itself, but this redirect is good behaviour, as you want every request to get redirected to https. In a redirect the headers are lost, but this is not caused by Really Simple SSL. This is just the redirect. The way to resolve it is to request the wp rest api over https. That way no redirect is needed. 

When you deactivate the plugin, you call the rest api over http, and the redirect is not enforced. As a result the problem is gone, but you connect insecurely. 

A workaround is to disable the rest api redirect by adding this constant:
define('rsssl_no_rest_api_redirect', true);

But as it gives the option to connect over http, this is not the recommended solution.

**Comment by amirvenus** [comment]
Now I can connect using http but not https as it complains about the signature. 

Is there any other way to have the plugin enabled and connect to the REST API through HTTPS at the same time?

**Comment by rlankhorst** [comment]
I'm not sure what you mean by that it complains about the signature? Is your SSL certificate not valid?

What did you change? Did you use the constant to disable the rest api redirect?
