### ISSUE TITLE
My letsencrypt certs are not detected

### ISSUE THREAD

**Issue by kornelc** [rlankhorst/really-simple-ssl#230]
Hi,
I generated certs via letsencryot and manually copied them into /etc/ssl/certs/fullchain.pem and /etc/ssl/private/privkey.pem. I tried activating the plugin but it could not find them.
Then I manually modified the default ssl file in sites available and symlinked it to sites enabled. The relevant ssl conf looks like this:
SSLCertificateFile	/etc/ssl/certs/fullchain.pem
SSLCertificateKeyFile /etc/ssl/private/privkey.pem
Then I deactivated the plugin and activated again, but it could not find my certs.
I saw the post about wp-encrypt, but I already have my certs. Is there any simple thing I can do to make the them detectable by Really Simple SSL (like giving it a name and location it's looking for), or to manually tell apache to use them some how. They are all there, just not found/detected by either Apache or Really Simple SSL.
(I have full shell access)

Any help would be greatly appreciated.
Thanks in advance!

**Comment by mwolters90** [comment]
Hi,

Really Simple SSL will be able to detect the certificate when Apache can detect is as well. As long as Apache cannot detect the certificate, Really Simple SSL cannot detect it either. This has to be fixed in Apache, it sounds like the certificate is not installed correctly, for example with an incorrect path. Another possibility is an incorrectly configured Apache server that has port 443 closed. You can always contact your hosting provider so they can check the configuration for you.

**Comment by kornelc** [comment]
Thanks Mark,

I figured it out. The problem was that I didn’t enable the SSL module: a2enmod ssl.
